// Mocks generated by Mockito 5.3.2 from annotations
// in avistaouaprazo/test/feature/vistaOuPrazo/usecases/calcular_valor_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:avistaouaprazo/core/error/falhas.dart' as _i5;
import 'package:avistaouaprazo/core/util/convert_to_string_real.dart' as _i7;
import 'package:avistaouaprazo/features/vistaOuPrazo/domain/entities/taxas.dart'
    as _i6;
import 'package:avistaouaprazo/features/vistaOuPrazo/domain/repositories/vista_ou_prazo_repository.dart'
    as _i3;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [VistaOuPrazoRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockVistaOuPrazoRepository extends _i1.Mock
    implements _i3.VistaOuPrazoRepository {
  @override
  _i4.Future<_i2.Either<_i5.Falha, _i6.Taxas>> getTaxas() =>
      (super.noSuchMethod(
        Invocation.method(
          #getTaxas,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Falha, _i6.Taxas>>.value(
            _FakeEither_0<_i5.Falha, _i6.Taxas>(
          this,
          Invocation.method(
            #getTaxas,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.Either<_i5.Falha, _i6.Taxas>>.value(
                _FakeEither_0<_i5.Falha, _i6.Taxas>(
          this,
          Invocation.method(
            #getTaxas,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Falha, _i6.Taxas>>);
}

/// A class which mocks [ConvertToStringReal].
///
/// See the documentation for Mockito's code generation for more information.
class MockConvertToStringReal extends _i1.Mock
    implements _i7.ConvertToStringReal {
  @override
  String fromDoubleToStringReal(double? valor) => (super.noSuchMethod(
        Invocation.method(
          #fromDoubleToStringReal,
          [valor],
        ),
        returnValue: '',
        returnValueForMissingStub: '',
      ) as String);
}
