// Mocks generated by Mockito 5.3.2 from annotations
// in avistaouaprazo/test/features/vistaOuPrazo/data/repositories/vista_ou_prazo_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:avistaouaprazo/core/network/network_info.dart' as _i6;
import 'package:avistaouaprazo/features/vistaOuPrazo/data/datasources/vista_ou_prazo_local_data_source.dart'
    as _i5;
import 'package:avistaouaprazo/features/vistaOuPrazo/data/datasources/vista_ou_prazo_remote_data_source.dart'
    as _i3;
import 'package:avistaouaprazo/features/vistaOuPrazo/data/models/taxas_model.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTaxasModel_0 extends _i1.SmartFake implements _i2.TaxasModel {
  _FakeTaxasModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [VistaOuPrazoRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockVistaOuPrazoRemoteDataSource extends _i1.Mock
    implements _i3.VistaOuPrazoRemoteDataSource {
  @override
  _i4.Future<_i2.TaxasModel> getRemoteTaxas() => (super.noSuchMethod(
        Invocation.method(
          #getRemoteTaxas,
          [],
        ),
        returnValue: _i4.Future<_i2.TaxasModel>.value(_FakeTaxasModel_0(
          this,
          Invocation.method(
            #getRemoteTaxas,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.TaxasModel>.value(_FakeTaxasModel_0(
          this,
          Invocation.method(
            #getRemoteTaxas,
            [],
          ),
        )),
      ) as _i4.Future<_i2.TaxasModel>);
}

/// A class which mocks [VistaOuPrazoLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockVistaOuPrazoLocalDataSource extends _i1.Mock
    implements _i5.VistaOuPrazoLocalDataSource {
  @override
  _i2.TaxasModel getCachedTaxas() => (super.noSuchMethod(
        Invocation.method(
          #getCachedTaxas,
          [],
        ),
        returnValue: _FakeTaxasModel_0(
          this,
          Invocation.method(
            #getCachedTaxas,
            [],
          ),
        ),
        returnValueForMissingStub: _FakeTaxasModel_0(
          this,
          Invocation.method(
            #getCachedTaxas,
            [],
          ),
        ),
      ) as _i2.TaxasModel);
  @override
  _i4.Future<bool> cacheTaxas(_i2.TaxasModel? taxasModel) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheTaxas,
          [taxasModel],
        ),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
  @override
  bool cacheIsvalido() => (super.noSuchMethod(
        Invocation.method(
          #cacheIsvalido,
          [],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
        returnValueForMissingStub: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
